export const categoryArray = [
  { id: 0, params: "" },
  { id: 1, params: "attraction" },
  { id: 2, params: "culture" },
  { id: 3, params: "shopping" },
  { id: 4, params: "restaurant" },
  { id: 5, params: "leisure" },
  { id: 6, params: "festival" },
];

export const districtArray = [
  { id: 0, params: "" },
  { id: 1, params: "gangnam" },
  { id: 2, params: "gangdong" },
  { id: 3, params: "gangbuk" },
  { id: 4, params: "gangseo" },
  { id: 5, params: "gwanak" },
  { id: 6, params: "gwangjin" },
  { id: 7, params: "guro" },
  { id: 8, params: "geumcheon" },
  { id: 9, params: "nowon" },
  { id: 10, params: "dobong" },
  { id: 11, params: "dongdaemun" },
  { id: 12, params: "dongjak" },
  { id: 13, params: "mapo" },
  { id: 14, params: "seodaemun" },
  { id: 15, params: "seocho" },
  { id: 16, params: "seongdong" },
  { id: 17, params: "seongbuk" },
  { id: 18, params: "songpa" },
  { id: 19, params: "yangcheon" },
  { id: 20, params: "yeongdeungpo" },
  { id: 21, params: "yongsan" },
  { id: 22, params: "eunpyeong" },
  { id: 23, params: "jongno" },
  { id: 24, params: "junggu" },
  { id: 25, params: "jungnang" },
];
