export const InterestData = [
  {
    category: "Art",
    interests: [
      { id: 0, inter: "Fashion", selected: false },
      { id: 1, inter: "Beauty", selected: false },
      { id: 2, inter: "Design", selected: false },
      { id: 3, inter: "Picture", selected: false },
      { id: 4, inter: "Exhibition", selected: false },
      { id: 5, inter: "Room Interior", selected: false },
    ],
  },
  {
    category: "Career",
    interests: [
      { id: 6, inter: "Education", selected: false },
      { id: 7, inter: "IT", selected: false },
      { id: 8, inter: "Programming", selected: false },
      { id: 9, inter: "Marketing", selected: false },
      { id: 10, inter: "Startup", selected: false },
      { id: 11, inter: "Internship", selected: false },
      { id: 12, inter: "Hr", selected: false },
    ],
  },
  {
    category: "Entertainment",
    interests: [
      { id: 13, inter: "Movies", selected: false },
      { id: 14, inter: "Kpop", selected: false },
      { id: 15, inter: "Animation", selected: false },
      { id: 16, inter: "Social Media", selected: false },
      { id: 17, inter: "Game", selected: false },
      { id: 18, inter: "Video Streaming", selected: false },
      { id: 19, inter: "Drama", selected: false },
      { id: 20, inter: "Webtoon", selected: false },
      { id: 21, inter: "Singing", selected: false },
      { id: 22, inter: "Music", selected: false },
      { id: 23, inter: "Eating", selected: false },
    ],
  },
  {
    category: "Food",
    interests: [
      { id: 24, inter: "Korean", selected: false },
      { id: 25, inter: "Chinese", selected: false },
      { id: 26, inter: "Italian", selected: false },
      { id: 27, inter: "Mexican", selected: false },
      { id: 28, inter: "Japanese", selected: false },
      { id: 29, inter: "Coffee", selected: false },
      { id: 30, inter: "Dessert", selected: false },
      { id: 31, inter: "Drink", selected: false },
    ],
  },
  {
    category: "Hobbies",
    interests: [
      { id: 32, inter: "Travel", selected: false },
      { id: 33, inter: "Language", selected: false },
      { id: 34, inter: "Reading", selected: false },
      { id: 35, inter: "Shopping", selected: false },
      { id: 36, inter: "Driving", selected: false },
      { id: 37, inter: "DIY", selected: false },
    ],
  },
  {
    category: "Lifestyle",
    interests: [
      { id: 38, inter: "Socializing", selected: false },
      { id: 39, inter: "Homebody", selected: false },
      { id: 40, inter: "Walk", selected: false },
      { id: 41, inter: "Pet", selected: false },
      { id: 42, inter: "Fitness", selected: false },
      { id: 43, inter: "Camping", selected: false },
      { id: 44, inter: "Picnic", selected: false },
      { id: 45, inter: "Vegan", selected: false },
      { id: 46, inter: "Volunteer", selected: false },
    ],
  },
  {
    category: "Sports",
    interests: [
      { id: 47, inter: "Fitness", selected: false },
      { id: 48, inter: "Dance", selected: false },
      { id: 49, inter: "Basketball", selected: false },
      { id: 50, inter: "Volleyball", selected: false },
      { id: 51, inter: "Running", selected: false },
      { id: 52, inter: "Swimming", selected: false },
      { id: 53, inter: "Baseball", selected: false },
      { id: 54, inter: "Bicycle", selected: false },
      { id: 55, inter: "Climbing", selected: false },
      { id: 56, inter: "Bowling", selected: false },
      { id: 57, inter: "Yoga", selected: false },
      { id: 58, inter: "Pilates", selected: false },
      { id: 59, inter: "Jiujitsu", selected: false },
      { id: 60, inter: "Golf", selected: false },
      { id: 62, inter: "Surfing", selected: false },
      { id: 63, inter: "Skateboard", selected: false },
      { id: 64, inter: "Skiing", selected: false },
      { id: 65, inter: "Climbing", selected: false },
      { id: 66, inter: "Crossfit", selected: false },
    ],
  },
];
