export const InterestData = [
  {
    category: "Art & Beauty",
    interests: [
      { id: 0, inter: "MUSIC", selected: false },
      { id: 1, inter: "PICTURE", selected: false },
      { id: 2, inter: "FASHION", selected: false },
      { id: 3, inter: "PICTUREGI", selected: false },
      { id: 4, inter: "MAKEUP", selected: false },
      { id: 5, inter: "BEAUTY", selected: false },
      { id: 6, inter: "VIEWING_EXHIBITION", selected: false },
      { id: 7, inter: "DESIGN", selected: false },
      { id: 8, inter: "PILKA", selected: false },
      { id: 9, inter: "INTERIOR", selected: false },
      { id: 10, inter: "POLAROID", selected: false },
    ],
  },

  {
    category: "Activities & Investment & Tech",
    interests: [
      { id: 11, inter: "BUSINESS", selected: false },
      { id: 12, inter: "STOCK", selected: false },
      { id: 13, inter: "INVESTMENT", selected: false },
      { id: 14, inter: "REAL_ESTATE", selected: false },
      { id: 15, inter: "BITCOIN", selected: false },
    ],
  },
  {
    category: "Career & Major",
    interests: [
      { id: 16, inter: "STUD", selected: false },
      { id: 17, inter: "WORK_LIFE", selected: false },
      { id: 18, inter: "LANGUAGE", selected: false },
      { id: 19, inter: "EDUCATION", selected: false },
      { id: 20, inter: "DESIGN", selected: false },
      { id: 21, inter: "IT", selected: false },
      { id: 22, inter: "JOB", selected: false },
      { id: 23, inter: "PART_TIME", selected: false },
      { id: 24, inter: "MEDICINE", selected: false },
      { id: 25, inter: "PROGRAMMING", selected: false },
      { id: 26, inter: "CHANGING", selected: false },
      { id: 27, inter: "MARKETING", selected: false },
      { id: 28, inter: "STARTUP", selected: false },
      { id: 29, inter: "INTERN", selected: false },
      { id: 30, inter: "HR", selected: false },
    ],
  },
  {
    category: "Entertainment",
    interests: [
      { id: 31, inter: "MOVIE", selected: false },
      { id: 32, inter: "NETFLIX", selected: false },
      { id: 33, inter: "KPOP", selected: false },
      { id: 34, inter: "ANIMATION", selected: false },
      { id: 35, inter: "INSTAGRAM", selected: false },
      { id: 36, inter: "GAME", selected: false },
      { id: 37, inter: "YOUTUBE", selected: false },
      { id: 38, inter: "DRAMA", selected: false },
      { id: 39, inter: "WEBTOON", selected: false },
      { id: 40, inter: "SINGING", selected: false },
      { id: 41, inter: "DISNEY", selected: false },
      { id: 42, inter: "INSTRUMENTAL_MUSIC", selected: false },
      { id: 43, inter: "EATING", selected: false },
      { id: 44, inter: "HARRY_POTTER", selected: false },
      { id: 45, inter: "MARVEL", selected: false },
      { id: 46, inter: "LOL", selected: false },
      { id: 47, inter: "NINTENDO", selected: false },
      { id: 48, inter: "PLAYSTATION", selected: false },
      { id: 49, inter: "STEAM", selected: false },
      { id: 50, inter: "PUBG", selected: false },
      { id: 51, inter: "PERFORMANCE", selected: false },
    ],
  },
  {
    category: "Food",
    interests: [
      { id: 52, inter: "RESTAURANT", selected: false },
      { id: 53, inter: "COFFEE", selected: false },
      { id: 54, inter: "DESSERT", selected: false },
      { id: 55, inter: "SUSHI", selected: false },
      { id: 56, inter: "ALCOHOL", selected: false },
      { id: 57, inter: "CHICKEN", selected: false },
      { id: 58, inter: "TTEOKBOKKI", selected: false },
      { id: 59, inter: "BEER", selected: false },
      { id: 60, inter: "PASTA", selected: false },
      { id: 61, inter: "BREAD", selected: false },
      { id: 62, inter: "HAMBURGER", selected: false },
      { id: 63, inter: "SALAD", selected: false },
      { id: 64, inter: "WINE", selected: false },
      { id: 65, inter: "WHISKEY", selected: false },
    ],
  },
  {
    category: "Hobbies & Interests",
    interests: [
      { id: 66, inter: "TRAVEL", selected: false },
      { id: 67, inter: "LANGUAGE_EXCHANGE", selected: false },
      { id: 68, inter: "LANGUAGE", selected: false },
      { id: 69, inter: "READING", selected: false },
      { id: 70, inter: "SHOPPING", selected: false },
      { id: 71, inter: "DRIVE", selected: false },
      { id: 72, inter: "DIY", selected: false },
    ],
  },
  {
    category: "Lifestyle",
    interests: [
      { id: 73, inter: "LIGHTHEARTED", selected: false },
      { id: 74, inter: "MAKING_FRIENDS", selected: false },
      { id: 75, inter: "STAYING_HOME", selected: false },
      { id: 76, inter: "DATING", selected: false },
      { id: 77, inter: "CAT_BUTLER", selected: false },
      { id: 78, inter: "WALK", selected: false },
      { id: 79, inter: "DOG", selected: false },
      { id: 80, inter: "FAN", selected: false },
      { id: 81, inter: "PET", selected: false },
      { id: 82, inter: "DIET", selected: false },
      { id: 83, inter: "MARRIAGE", selected: false },
      { id: 84, inter: "CHILD_CARE", selected: false },
    ],
  },
  {
    category: "Sports",
    interests: [
      { id: 85, inter: "FITNESS", selected: false },
      { id: 86, inter: "DANCE", selected: false },
      { id: 87, inter: "BASKETBALL", selected: false },
      { id: 88, inter: "VOLLEYBALL", selected: false },
      { id: 89, inter: "RUNNING", selected: false },
      { id: 90, inter: "SWIMMING", selected: false },
      { id: 91, inter: "BASEBALL", selected: false },
      { id: 92, inter: "BICYCLE", selected: false },
      { id: 93, inter: "CLIMBING1", selected: false },
      { id: 94, inter: "BOWLING", selected: false },
      { id: 95, inter: "YOGA", selected: false },
      { id: 96, inter: "PILATES", selected: false },
      { id: 97, inter: "JOUJITSU", selected: false },
      { id: 98, inter: "GOLF", selected: false },
      { id: 99, inter: "SURFING", selected: false },
      { id: 100, inter: "SKATEBOARD", selected: false },
      { id: 101, inter: "SKI", selected: false },
      { id: 102, inter: "CLIMBING2", selected: false },
      { id: 103, inter: "CROSSFIT", selected: false },
    ],
  },
  {
    category: "Wellbeing",
    interests: [
      { id: 104, inter: "HEALTH", selected: false },
      { id: 105, inter: "CAMPING", selected: false },
      { id: 106, inter: "MEDITATION", selected: false },
      { id: 107, inter: "PICNIC", selected: false },
      { id: 108, inter: "ENVIRONMENTAL", selected: false },
      { id: 109, inter: "PROTECTION", selected: false },
      { id: 110, inter: "VEGAN", selected: false },
      { id: 111, inter: "VOLUNTEER", selected: false },
    ],
  },
];
