export const languageArray: string[] = [
  "English",
  "Korean",
  "Japanese",
  "Chinese",
  "Spanish",
  "French",
  "German",
  "Russian",
  "Portuguese",
  "Italian",
  "Vietnamese",
  "Thai",
  "Indonesian",
  "Hindi",
];

export type InterestType = {
  id: number;
  group: interestGroupType;
  element: string;
};
export const interestArray: InterestType[] = [
  { id: 0, group: "artBeauty", element: "FASHION" },
  { id: 1, group: "artBeauty", element: "BEAUTY" },
  { id: 2, group: "artBeauty", element: "DESIGN" },
  { id: 3, group: "artBeauty", element: "PICTURE" },
  { id: 4, group: "artBeauty", element: "EXHIBITION" },
  { id: 5, group: "artBeauty", element: "ROOM_INTERIOR" },
  { id: 6, group: "careerMajor", element: "EDUCATION" },
  { id: 7, group: "careerMajor", element: "IT" },
  { id: 8, group: "careerMajor", element: "PROGRAMMING" },
  { id: 9, group: "careerMajor", element: "MARKETING" },
  { id: 10, group: "careerMajor", element: "STARTUP" },
  { id: 11, group: "careerMajor", element: "INTERNSHIP" },
  { id: 12, group: "careerMajor", element: "HR" },
  { id: 13, group: "entertainment", element: "MOVIES" },
  { id: 14, group: "entertainment", element: "KPOP" },
  { id: 15, group: "entertainment", element: "ANIMATION" },
  { id: 16, group: "entertainment", element: "SOCIAL_MEDIA" },
  { id: 17, group: "entertainment", element: "GAME" },
  { id: 18, group: "entertainment", element: "VIDEO_STREAMING" },
  { id: 19, group: "entertainment", element: "DRAMA" },
  { id: 20, group: "entertainment", element: "WEBTOON" },
  { id: 21, group: "entertainment", element: "SINGING" },
  { id: 22, group: "entertainment", element: "MUSIC" },
  { id: 23, group: "entertainment", element: "EATING" },
  { id: 24, group: "food", element: "KOREAN" },
  { id: 25, group: "food", element: "CHINESE" },
  { id: 26, group: "food", element: "ITALIAN" },
  { id: 27, group: "food", element: "MEXICAN" },
  { id: 28, group: "food", element: "JAPANESE" },
  { id: 29, group: "food", element: "COFFEE" },
  { id: 30, group: "food", element: "DESSERT" },
  { id: 31, group: "food", element: "DRINK" },
  { id: 32, group: "hobbiesInterests", element: "TRAVEL" },
  { id: 33, group: "hobbiesInterests", element: "LANGUAGE" },
  { id: 34, group: "hobbiesInterests", element: "READING" },
  { id: 35, group: "hobbiesInterests", element: "SHOPPING" },
  { id: 36, group: "hobbiesInterests", element: "DRIVING" },
  { id: 37, group: "hobbiesInterests", element: "DIY" },
  { id: 38, group: "lifestyle", element: "SOCIALIZING" },
  { id: 39, group: "lifestyle", element: "HOMEBODY" },
  { id: 40, group: "lifestyle", element: "WALK" },
  { id: 41, group: "lifestyle", element: "PET" },
  { id: 42, group: "lifestyle", element: "FITNESS" },
  { id: 43, group: "lifestyle", element: "CAMPING" },
  { id: 44, group: "lifestyle", element: "PICNIC" },
  { id: 45, group: "lifestyle", element: "VEGAN" },
  { id: 46, group: "lifestyle", element: "VOLUNTEER" },
  { id: 47, group: "sports", element: "DANCE" },
  { id: 48, group: "sports", element: "BASKETBALL" },
  { id: 49, group: "sports", element: "VOLLEYBALL" },
  { id: 50, group: "sports", element: "RUNNING" },
  { id: 51, group: "sports", element: "SWIMMING" },
  { id: 52, group: "sports", element: "BASEBALL" },
  { id: 53, group: "sports", element: "BICYCLE" },
  { id: 54, group: "sports", element: "CLIMBING" },
  { id: 55, group: "sports", element: "BOWLING" },
  { id: 56, group: "sports", element: "YOGA" },
  { id: 57, group: "sports", element: "PILATES" },
  { id: 58, group: "sports", element: "JIUJITSU" },
  { id: 59, group: "sports", element: "GOLF" },
  { id: 60, group: "sports", element: "SURFING" },
  { id: 61, group: "sports", element: "SKATEBOARD" },
  { id: 62, group: "sports", element: "SKIING" },
  { id: 63, group: "sports", element: "CROSSFIT" },
];
