export const AdditionalInformationTypeArray = [
  {
    category: "Attraction",
    contents: [
      { key: "accomcount", text: "Accommodation count" },
      { key: "infocenter", text: "Information center" },
      { key: "parking", text: "Parking" },
      { key: "expagerange", text: "Experience age range" },
      { key: "expguide", text: "Experience guide" },
      { key: "opendate", text: "Open date" },
      { key: "restdate", text: "Rest date" },
      { key: "usetime", text: "Use time" },
      { key: "useseason", text: "Use season" },
    ],
  },
  {
    category: "Culture",
    contents: [
      { key: "accomcountculture", text: "Accommodation count" },
      { key: "infocenterculture", text: "Information center" },
      { key: "parkingculture", text: "Parking" },
      { key: "parkingfee", text: "Parking fee" },
      { key: "restdateculture", text: "Rest date" },
      { key: "scale", text: "Scale" },
      { key: "usefee", text: "Use fee" },
      { key: "spendtime", text: "Spend time" },
      { key: "usetimeculture", text: "Use time" },
    ],
  },
  {
    category: "Shopping",
    contents: [
      { key: "fairday", text: "Fair day" },
      { key: "infocentershopping", text: "Information center" },
      { key: "opendateshopping", text: "Open date" },
      { key: "opentime", text: "Open time" },
      { key: "parkingshopping", text: "Parking" },
      { key: "restdateshopping", text: "Rest date" },
      { key: "restroom", text: "Restroom" },
      { key: "saleitem", text: "Sale item" },
      { key: "scaleshopping", text: "Scale" },
      { key: "shopguide", text: "Shop guide" },
    ],
  },
  {
    category: "Restaurant",
    contents: [
      { key: "treatmenu", text: "Treating menu" },
      { key: "infocenterfood", text: "Information center" },
      { key: "reservationfood", text: "Reservation" },
      { key: "parkingfood", text: "Parking" },
      { key: "opendatefood", text: "Open date" },
      { key: "lcnsno", text: "License number" },
      { key: "seat", text: "Seat" },
      { key: "scalefood", text: "Scale" },
      { key: "firstmenu", text: "First menu" },
      { key: "smoking", text: "Smoking" },
      { key: "opentimefood", text: "Open time" },
      { key: "restdatefood", text: "Rest date" },
    ],
  },
  {
    category: "Leisure",
    contents: [
      { key: "accomcountleports", text: "Accommodation count" },
      { key: "infocenterleports", text: "Information center" },
      { key: "parkingleports", text: "Parking" },
      { key: "parkingfeeleports", text: "Parking Fee" },
      { key: "expagerangeleports", text: "Experience age range" },
      { key: "scaleleports", text: "Scale" },
      { key: "reservation", text: "Reservation" },
      { key: "openperiod", text: "Open period" },
      { key: "restdateleports", text: "Rest date" },
      { key: "usetimeleports", text: "Use time" },
      { key: "usefeeleports", text: "Use fee" },
    ],
  },
  {
    category: "Festival",
    contents: [
      { key: "agelimit", text: "Age limit" },
      { key: "bookingplace", text: "Booking place" },
      { key: "discountinfofestival", text: "Discount information" },
      { key: "eventstartdate", text: "Event start date" },
      { key: "eventenddate", text: "Event end date" },
      { key: "eventhomepage", text: "Event homepage" },
      { key: "eventplace", text: "Event place" },
      { key: "placeinfo", text: "Place information" },
      { key: "playtime", text: "Play time" },
      { key: "program", text: "Program" },
      { key: "subevent", text: "Sub-event" },
      { key: "spendtimefestival", text: "Spend time" },
      { key: "usetimefestival", text: "Use time" },
      { key: "sponsor1", text: "Sponsor 1" },
      { key: "sponsor1tel", text: "Sponsor 1 tel" },
      { key: "sponsor2", text: "Sponsor 2" },
      { key: "sponsor2tel", text: "Sponsor 2 tel" },
    ],
  },
];
