export const matesArrayK: PickedMatesType[] = [
  {
    id: 1,
    nickname: "Jo",
    username: "kakao_2980242960",
    email: "abc@gmail.com",
    profileImageUrl:
      "https://images.unsplash.com/photo-1692651743307-191e905a0ea6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY5MzI4OTc5Mg&ixlib=rb-4.0.3&q=80&w=1080",
    roleType: "K-Buddy",
    providerType: "KAKAO",
    createdDate: "2023-08-29T03:31:43.674109",
    modifiedDate: null,
  },
  {
    id: 2,
    nickname: "Jeong",
    username: "kakao_2980242960",
    email: "abc@gmail.com",
    profileImageUrl:
      "https://images.unsplash.com/photo-1689852484069-3e0fe82cc7c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY5MzI4OTgyMA&ixlib=rb-4.0.3&q=80&w=1080",
    roleType: "K-Buddy",
    providerType: "KAKAO",
    createdDate: "2023-08-29T03:31:43.674109",
    modifiedDate: null,
  },
  {
    id: 3,
    nickname: "Lee",
    username: "kakao_2980242960",
    email: "abc@gmail.com",
    profileImageUrl:
      "https://images.unsplash.com/photo-1691858019962-303a7094a581?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY5MzI4OTg3NQ&ixlib=rb-4.0.3&q=80&w=1080",
    roleType: "K-Buddy",
    providerType: "KAKAO",
    createdDate: "2023-08-29T03:31:43.674109",
    modifiedDate: null,
  },
  {
    id: 4,
    nickname: "Kim",
    username: "kakao_2980242960",
    email: "abc@gmail.com",
    profileImageUrl:
      "https://images.unsplash.com/photo-1692791256961-b8797139ba2c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY5MzI4OTg4Ng&ixlib=rb-4.0.3&q=80&w=1080",
    roleType: "K-Buddy",
    providerType: "KAKAO",
    createdDate: "2023-08-29T03:31:43.674109",
    modifiedDate: null,
  },
  {
    id: 5,
    nickname: "Park",
    username: "kakao_2980242960",
    email: "abc@gmail.com",
    profileImageUrl:
      "https://images.unsplash.com/photo-1691862866986-676a808a6441?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY5MzI4OTg5Nw&ixlib=rb-4.0.3&q=80&w=1080",
    roleType: "K-Buddy",
    providerType: "KAKAO",
    createdDate: "2023-08-29T03:31:43.674109",
    modifiedDate: null,
  },
  {
    id: 6,
    nickname: "Choi",
    username: "kakao_2980242960",
    email: "abc@gmail.com",
    profileImageUrl:
      "https://images.unsplash.com/photo-1691156564254-e503d146ac97?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY5MzI4OTkwNg&ixlib=rb-4.0.3&q=80&w=1080",
    roleType: "K-Buddy",
    providerType: "KAKAO",
    createdDate: "2023-08-29T03:31:43.674109",
    modifiedDate: null,
  },
];

export const matesArrayT: PickedMatesType[] = [
  {
    id: 1,
    nickname: "jenny",
    username: "kakao_2980242960",
    email: "abc@gmail.com",
    profileImageUrl:
      "https://images.unsplash.com/photo-1691155056059-82a814c79240?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY5MzI4OTkxMw&ixlib=rb-4.0.3&q=80&w=1080",
    roleType: "Traveler",
    providerType: "KAKAO",
    createdDate: "2023-08-29T03:31:43.674109",
    modifiedDate: null,
  },
  {
    id: 2,
    nickname: "mark",
    username: "kakao_2980242960",
    email: "abc@gmail.com",
    profileImageUrl:
      "https://plus.unsplash.com/premium_photo-1676892435585-d29aee82ad6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY5MzI4OTkyMQ&ixlib=rb-4.0.3&q=80&w=1080",
    roleType: "Traveler",
    providerType: "KAKAO",
    createdDate: "2023-08-29T03:31:43.674109",
    modifiedDate: null,
  },
  {
    id: 3,
    nickname: "alice",
    username: "kakao_2980242960",
    email: "abc@gmail.com",
    profileImageUrl:
      "https://images.unsplash.com/photo-1681255633332-61b53fa198e4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY5MzI4OTkzMA&ixlib=rb-4.0.3&q=80&w=1080",
    roleType: "Traveler",
    providerType: "KAKAO",
    createdDate: "2023-08-29T03:31:43.674109",
    modifiedDate: null,
  },
  {
    id: 4,
    nickname: "jane",
    username: "kakao_2980242960",
    email: "abc@gmail.com",
    profileImageUrl:
      "https://images.unsplash.com/photo-1692023383905-487b88c9bf0d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY5MzI4OTk0NQ&ixlib=rb-4.0.3&q=80&w=1080",
    roleType: "Traveler",
    providerType: "KAKAO",
    createdDate: "2023-08-29T03:31:43.674109",
    modifiedDate: null,
  },
];

export const AdditionalInformationTypeArray = [
  {
    category: "Attraction",
    contents: [
      { key: "accomcount", text: "Accommodation count" },
      { key: "infocenter", text: "Information center" },
      { key: "parking", text: "Parking" },
      { key: "expagerange", text: "Experience age range" },
      { key: "expguide", text: "Experience guide" },
      { key: "opendate", text: "Open date" },
      { key: "restdate", text: "Rest date" },
      { key: "usetime", text: "Use time" },
      { key: "useseason", text: "Use season" },
    ],
  },
  {
    category: "Culture",
    contents: [
      { key: "accomcountculture", text: "Accommodation count" },
      { key: "infocenterculture", text: "Information center" },
      { key: "parkingculture", text: "Parking" },
      { key: "parkingfee", text: "Parking fee" },
      { key: "restdateculture", text: "Rest date" },
      { key: "scale", text: "Scale" },
      { key: "usefee", text: "Use fee" },
      { key: "spendtime", text: "Spend time" },
      { key: "usetimeculture", text: "Use time" },
    ],
  },
  {
    category: "Shopping",
    contents: [
      { key: "fairday", text: "Fair day" },
      { key: "infocentershopping", text: "Information center" },
      { key: "opendateshopping", text: "Open date" },
      { key: "opentime", text: "Open time" },
      { key: "parkingshopping", text: "Parking" },
      { key: "restdateshopping", text: "Rest date" },
      { key: "restroom", text: "Restroom" },
      { key: "saleitem", text: "Sale item" },
      { key: "scaleshopping", text: "Scale" },
      { key: "shopguide", text: "Shop guide" },
    ],
  },
  {
    category: "Restaurant",
    contents: [
      { key: "treatmenu", text: "Treating menu" },
      { key: "infocenterfood", text: "Information center" },
      { key: "reservationfood", text: "Reservation" },
      { key: "parkingfood", text: "Parking" },
      { key: "opendatefood", text: "Open date" },
      { key: "lcnsno", text: "License number" },
      { key: "seat", text: "Seat" },
      { key: "scalefood", text: "Scale" },
      { key: "firstmenu", text: "First menu" },
      { key: "smoking", text: "Smoking" },
      { key: "opentimefood", text: "Open time" },
      { key: "restdatefood", text: "Rest date" },
    ],
  },
  {
    category: "Leisure",
    contents: [
      { key: "accomcountleports", text: "Accommodation count" },
      { key: "infocenterleports", text: "Information center" },
      { key: "parkingleports", text: "Parking" },
      { key: "parkingfeeleports", text: "Parking Fee" },
      { key: "expagerangeleports", text: "Experience age range" },
      { key: "scaleleports", text: "Scale" },
      { key: "reservation", text: "Reservation" },
      { key: "openperiod", text: "Open period" },
      { key: "restdateleports", text: "Rest date" },
      { key: "usetimeleports", text: "Use time" },
      { key: "usefeeleports", text: "Use fee" },
    ],
  },
  {
    category: "Festival",
    contents: [
      { key: "agelimit", text: "Age limit" },
      { key: "bookingplace", text: "Booking place" },
      { key: "discountinfofestival", text: "Discount information" },
      { key: "eventstartdate", text: "Event start date" },
      { key: "eventenddate", text: "Event end date" },
      { key: "eventhomepage", text: "Event homepage" },
      { key: "eventplace", text: "Event place" },
      { key: "placeinfo", text: "Place information" },
      { key: "playtime", text: "Play time" },
      { key: "program", text: "Program" },
      { key: "subevent", text: "Sub-event" },
      { key: "spendtimefestival", text: "Spend time" },
      { key: "usetimefestival", text: "Use time" },
      { key: "sponsor1", text: "Sponsor 1" },
      { key: "sponsor1tel", text: "Sponsor 1 tel" },
      { key: "sponsor2", text: "Sponsor 2" },
      { key: "sponsor2tel", text: "Sponsor 2 tel" },
    ],
  },
];
