type wellbeingType =
  | "NOT_SELECTED"
  | "HEALTH"
  | "CAMPING"
  | "MEDITATION"
  | "PICNIC"
  | "ENVIRONMENTAL"
  | "PROTECTION"
  | "VEGAN"
  | "VOLUNTEER";

type activitiesInvestmentTechType =
  | "NOT_SELECTED"
  | "BUSINESS"
  | "STOCK"
  | "INVESTMENT"
  | "REAL_ESTATE"
  | "BITCOIN";

type careerMajorType =
  | "STUDY"
  | "NOT_SELECTED"
  | "STUD"
  | "WORK_LIFE"
  | "LANGUAGE"
  | "EDUCATION"
  | "DESIGN"
  | "IT"
  | "JOB"
  | "PART_TIME"
  | "MEDICINE"
  | "PROGRAMMING"
  | "CHANGING"
  | "MARKETING"
  | "STARTUP"
  | "INTERN"
  | "HR";

type entertainmentType =
  | "NETFLIX"
  | "NOT_SELECTED"
  | "MOVIE"
  | "NETFLIX"
  | "KPOP"
  | "ANIMATION"
  | "INSTAGRAM"
  | "GAME"
  | "YOUTUBE"
  | "DRAMA"
  | "WEBTOON"
  | "SINGING"
  | "DISNEY"
  | "INSTRUMENTAL_MUSIC"
  | "EATING"
  | "HARRY_POTTER"
  | "MARVEL"
  | "LOL"
  | "NINTENDO"
  | "PLAYSTATION"
  | "STEAM"
  | "PUBG"
  | "PERFORMANCE";

type hobbiesInterestsType =
  | "NOT_SELECTED"
  | "SHOPPING"
  | "TRAVEL"
  | "LANGUAGE_EXCHANGE"
  | "LANGUAGE"
  | "READING"
  | "DRIVE"
  | "DIY";

type lifestyleType =
  | "NOT_SELECTED"
  | "LIGHTHEARTED"
  | "MAKING_FRIENDS"
  | "STAYING_HOME"
  | "DATING"
  | "CAT_BUTLER"
  | "WALK"
  | "DOG"
  | "FAN"
  | "PET"
  | "DIET"
  | "MARRIAGE"
  | "CHILD_CARE";

type artBeautyType =
  | "NOT_SELECTED"
  | "MUSIC"
  | "PICTURE"
  | "FASHION"
  | "PICTUREGI"
  | "MAKEUP"
  | "BEAUTY"
  | "VIEWING_EXHIBITION"
  | "DESIGN"
  | "PILKA"
  | "INTERIOR"
  | "POLAROID";

type foodType =
  | "NOT_SELECTED"
  | "RESTAURANT"
  | "COFFEE"
  | "DESSERT"
  | "SUSHI"
  | "ALCOHOL"
  | "CHICKEN"
  | "TTEOKBOKKI"
  | "BEER"
  | "PASTA"
  | "BREAD"
  | "HAMBURGER"
  | "SALAD"
  | "WINE"
  | "WHISKEY";

type sportsType =
  | "NOT_SELECTED"
  | "FITNESS"
  | "DANCE"
  | "BASKETBALL"
  | "VOLLEYBALL"
  | "RUNNING"
  | "SWIMMING"
  | "BASEBALL"
  | "BICYCLE"
  | "CLIMBING1"
  | "BOWLING"
  | "YOGA"
  | "PILATES"
  | "JOUJITSU"
  | "GOLF"
  | "SURFING"
  | "SKATEBOARD"
  | "SKI"
  | "CLIMBING2"
  | "CROSSFIT";
