export const subjectData = [
  { id: 1, subject: "join us" },
  { id: 2, subject: "food" },
  { id: 3, subject: "nature" },
  { id: 4, subject: "k-pop" },
  { id: 5, subject: "attraction" },
  { id: 6, subject: "entertainment" },
  { id: 7, subject: "shopping" },
  { id: 8, subject: "leisure sports" },
  { id: 9, subject: "health and safety" },
  { id: 10, subject: "convenience facilities" },
  { id: 11, subject: "public transportation" },
  { id: 12, subject: "travel tips" },
];

export const regionData = [
  { id: 1, name: "Dobong" },
  { id: 2, name: "Dongdaemun" },
  { id: 3, name: "Dongjak" },
  { id: 4, name: "Eunpyeong" },
  { id: 5, name: "Gangbuk" },
  { id: 6, name: "Gangdong" },
  { id: 7, name: "Gangnam" },
  { id: 8, name: "Gangseo" },
  { id: 9, name: "Geumcheon" },
  { id: 10, name: "Guro" },
  { id: 11, name: "Gwanak" },
  { id: 12, name: "Gwangjin" },
  { id: 13, name: "Jongno" },
  { id: 14, name: "Junggu" },
  { id: 15, name: "Jungnang" },
  { id: 16, name: "Mapo" },
  { id: 17, name: "Nowon" },
  { id: 18, name: "Seocho" },
  { id: 19, name: "Seodaemun" },
  { id: 20, name: "Seongbuk" },
  { id: 21, name: "Seongdong" },
  { id: 22, name: "Songpa" },
  { id: 23, name: "Yangcheon" },
  { id: 24, name: "Yeongdeungpo" },
  { id: 25, name: "Yongsan" },
];
