import profile from "@assets/auth/user.png";

export const chatListData = [
  {
    id: 0,
    imgUrl: profile,
    partner: "Jane",
    lastChat: "Made an appointment!",
    time: "5 minute ago",
    unRead: true,
  },
  {
    id: 1,
    imgUrl: profile,
    partner: "Jane",
    lastChat: "Made an appointment!",
    time: "5 minute ago",
    unRead: true,
  },
  {
    id: 2,
    imgUrl: profile,
    partner: "Jane",
    lastChat: "Made an appointment!",
    time: "5 minute ago",
    unRead: false,
  },
  {
    id: 3,
    imgUrl: profile,
    partner: "Jane",
    lastChat: "Made an appointment!",
    time: "5 minute ago",
    unRead: false,
  },
  {
    id: 4,
    imgUrl: profile,
    partner: "Jane",
    lastChat: "Made an appointment!",
    time: "5 minute ago",
    unRead: false,
  },
  {
    id: 4,
    imgUrl: profile,
    partner: "Jane",
    lastChat: "Made an appointment!",
    time: "5 minute ago",
    unRead: false,
  },
  {
    id: 4,
    imgUrl: profile,
    partner: "Jane",
    lastChat: "Made an appointment!",
    time: "5 minute ago",
    unRead: false,
  },
  {
    id: 4,
    imgUrl: profile,
    partner: "Jane",
    lastChat: "Made an appointment!",
    time: "5 minute ago",
    unRead: false,
  },
  {
    id: 4,
    imgUrl: profile,
    partner: "Jane",
    lastChat: "Made an appointment!",
    time: "5 minute ago",
    unRead: false,
  },
  {
    id: 4,
    imgUrl: profile,
    partner: "Jane",
    lastChat: "Made an appointment!",
    time: "5 minute ago",
    unRead: false,
  },
];
